# Generated by Django 6.0.4 on 2026-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(upload_to='medicine_images/')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
