# Generated by Django 6.0.4 on 2026-05-11 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('units', '0002_palliativeunit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedonation',
            name='selected_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.palliativeunit'),
        ),
    ]
