# Generated by Django 6.0.4 on 2026-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicinedonation_selected_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedonation',
            name='approvped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinedonation',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinedonation',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
