# Generated by Django 6.0.4 on 2026-05-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicinedonation_approvped_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinedonation',
            old_name='approvped_at',
            new_name='approved_at',
        ),
    ]
