# Generated by Django 6.0.4 on 2026-05-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_approvped_at_medicinedonation_approved_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitinventory',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
