# Generated by Django 6.0.5 on 2026-05-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_verified_user_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
    ]
