# Generated by Django 6.0.5 on 2026-05-24 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('user', '0004_remove_user_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_image', models.ImageField(upload_to='medicine_images/')),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Unit Review'), ('accepted', 'Accepted by Unit'), ('collected', 'Collected'), ('removed', 'Removed by Admin')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_donations', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_donations', to='unit.palliativeunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
