# Generated by Django 6.0.4 on 2026-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_medicinerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
