# Generated by Django 6.0.5 on 2026-05-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_medicinerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Unit Review'), ('accepted', 'Accepted by Unit'), ('collected', 'Collected'), ('removed', 'Removed by Admin'), ('cancelled', 'Cancelled ')], default='pending', max_length=20),
        ),
    ]
