# Generated by Django 6.0.4 on 2026-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_palliativeunit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palliativeunit',
            old_name='location',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='palliativeunit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palliativeunit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
