# Generated by Django 6.0.4 on 2026-05-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_rename_location_palliativeunit_location_name_and_more'),
        ('users', '0005_remove_user_location_user_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerequest',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_requests', to='units.palliativeunit'),
        ),
    ]
