# Generated by Django 6.0.4 on 2026-05-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_medicinerequest_assigned_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerequest',
            name='assigned_unit',
        ),
    ]
