# Generated by Django 6.0.4 on 2026-05-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_rename_location_palliativeunit_location_name_and_more'),
        ('users', '0007_remove_medicinerequest_assigned_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerequest',
            name='selected_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.palliativeunit'),
        ),
    ]
