# Generated by Django 6.0.4 on 2026-05-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_name_unitinventory_medicine_name'),
        ('units', '0003_rename_location_palliativeunit_location_name_and_more'),
        ('users', '0008_medicinerequest_selected_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinerequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='medicinerequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicinerequest',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='medicinerequest',
            name='selected_unit',
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='inventory',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitinventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='unit',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='units.palliativeunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
