# Generated by Django 6.0.5 on 2026-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('pickup_pending', 'Pickup Pending'), ('collected', 'Collected'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
